openapi: 3.0.3
info:
  title: SYSTEM SHOP`s TUTIPET
  description: >
    'This is a ***sample ecommerce app API***.
     You can find
     out more about Swagger at [swagger.io]
     (http://swagger.io).
     Description supports markdown markup. For example,
     you can
     use the `inline code` using back ticks.'
  version: 1.0.0
  contact:
    name: Team Support
    email: vtuan0612@gmail.com
externalDocs:
  description: Any document link you want to generate along with API.
  url: http://swagger.io
servers:
  - url: 'http://localhost:8080'
paths:
  
